---
skip_output:
  - meta # Skips lefthook version printing
  - empty_summary # Skips summary heading when there are no steps to run
  - execution # Skips printing any execution logs (but prints if the execution failed)
  - execution_out # Skips printing execution output (but still prints failed commands output)
  - skips # Skips "skip" printing (i.e. no files matched)
